# -*- coding: utf-8 -*-

[package]
edition         = "2018"
name            = "wolfsmuehle"
description     = "Wolfsm√ºhle - Board game"
version         = "1.0.0"
homepage        = "https://bues.ch/"
license         = "GPL-2.0-or-later"
readme          = "README.md"
repository      = "https://bues.ch/cgit/wolfsmuehle.git"
authors         = ["Michael Buesch <m@bues.ch>"]

categories      = []
keywords        = ["boardgame"]

exclude         = ["/maintenance/"]

[features]
default         = ["gui", "server"]
gui             = ["cairo-rs", "expect-exit", "gdk", "gio", "glib", "gtk"]
server          = []

[dependencies]
anyhow          = "1.0.36"
itertools       = "0.10.0"
libc            = "0.2.82"
rand            = "0.8.2"
structopt       = "0.3.21"

cairo-rs        = { version = "0.9.1", optional = true }
expect-exit     = { version = "0.2.0", optional = true }
gdk             = { version = "0.13.2", optional = true }
gio             = { version = "0.9.1", optional = true }
glib            = { version = "0.10.3", optional = true }
gtk             = { version = "0.9.2", optional = true }

[profile.release]
lto             = "thin"

# vim: ts=4 sw=4 expandtab
