[package]
name            = "wolfsmuehle"
description     = ""
version         = "1.0.0"
homepage        = "https://bues.ch/"
license         = "GPL-2.0-or-later"
readme          = "README.md"
repository      = "https://bues.ch/cgit/wolfsmuehle.git"
authors         = ["Michael Buesch <m@bues.ch>"]

categories      = []
keywords        = ["boardgame"]

exclude         = ["/maintenance/"]

edition         = "2018"

[dependencies]
anyhow          = "1.0.36"
cairo-rs        = "0.9.1"
expect-exit     = "0.2.0"
gdk             = "0.13.2"
gio             = "0.9.1"
glib            = "0.10.3"
gtk             = "0.9.2"
rand            = "0.8.0"
structopt       = "0.3.21"

# vim: ts=4 sw=4 expandtab
